module.exports = {
    initConnection: require('./client').init,
    setOnOriginDataReceivedCallback: require('./client').setOnOriginDataReceivedCallback,
    getConnectedModuleNames: require('./client').getConnectedModuleNames,
    acceleration: require('./modules/Acceleration'),
    control: require('./modules/Control'),
    display: require('./modules/Display'),
    driver: require('./modules/Driver'),
    hall: require('./modules/Hall'),
    led: require('./modules/LED'),
    lightBelt: require('./modules/LightBelt'),
    observer: require('./modules/Observer'),
    pulse: require('./modules/Pulse'),
    rfCommunication: require('./modules/RfCommunication'),
    rfTelecontroller: require('./modules/RfTelecontroller'),
    signal: require('./modules/Signal'),
    ultrasonic: require('./modules/Ultrasonic'),
    makeyMakey: require('./modules/MakeyMakey'),
    distance: require('./modules/Distance'),
    addResetListener: require("./client").addResetListener,
    clearResetListener: require("./client").clearResetListener,
    addDisconnectListener: require('./client').addDisconnectListener,
    addConnectSuccessListener: require('./client').addConnectSuccessListener
}